/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.6 at Thu Nov 25 16:25:23 2021. */

#include "BleProtocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DeviceOpenRequest_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, DeviceOpenRequest, pwd, pwd, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, DeviceOpenRequest, type, pwd, 0),
    PB_FIELD(  3, INT64   , SINGULAR, STATIC  , OTHER, DeviceOpenRequest, uid, type, 0),
    PB_FIELD(  4, INT64   , SINGULAR, STATIC  , OTHER, DeviceOpenRequest, timeStamp, uid, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, DeviceOpenRequest, phoneNo, timeStamp, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSetDeviceNameRequest_fields[16] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, DeviceSetDeviceNameRequest, name, name, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSetDeviceNameRequest, code, name, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, DeviceSetDeviceNameRequest, pairPWD, code, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, DeviceSetDeviceNameRequest, openPWD, pairPWD, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, DeviceSetDeviceNameRequest, openDelay, openPWD, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, DeviceSetDeviceNameRequest, alarmDelay, openDelay, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, DeviceSetDeviceNameRequest, installPurpose, alarmDelay, 0),
    PB_FIELD(  8, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSetDeviceNameRequest, mqttServer, installPurpose, 0),
    PB_FIELD(  9, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSetDeviceNameRequest, ntpServer, mqttServer, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, DeviceSetDeviceNameRequest, isdhcp, ntpServer, 0),
    PB_FIELD( 11, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSetDeviceNameRequest, ip, isdhcp, 0),
    PB_FIELD( 12, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSetDeviceNameRequest, gateway, ip, 0),
    PB_FIELD( 13, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSetDeviceNameRequest, mask, gateway, 0),
    PB_FIELD( 14, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSetDeviceNameRequest, dns, mask, 0),
    PB_FIELD( 15, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSetDeviceNameRequest, groupId, dns, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceSipInfoRequest_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, DeviceSipInfoRequest, centerSip, centerSip, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSipInfoRequest, sipServer, centerSip, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSipInfoRequest, sipAccount, sipServer, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSipInfoRequest, sipPwd, sipAccount, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSipInfoRequest, sipServerSpare, sipPwd, 0),
    PB_FIELD(  6, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSipInfoRequest, sipAccountSpare, sipServerSpare, 0),
    PB_FIELD(  7, STRING  , SINGULAR, CALLBACK, OTHER, DeviceSipInfoRequest, sipPwdSpare, sipAccountSpare, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceCommonResponse_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, DeviceCommonResponse, status, status, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, DeviceCommonResponse, reserved, status, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
