/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Thu Nov 25 16:25:23 2021. */

#ifndef PB_BLEPROTOCOL_PB_H_INCLUDED
#define PB_BLEPROTOCOL_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DeviceSipInfoRequest {
    pb_callback_t centerSip;
    pb_callback_t sipServer;
    pb_callback_t sipAccount;
    pb_callback_t sipPwd;
    pb_callback_t sipServerSpare;
    pb_callback_t sipAccountSpare;
    pb_callback_t sipPwdSpare;
/* @@protoc_insertion_point(struct:DeviceSipInfoRequest) */
} DeviceSipInfoRequest;

typedef struct _DeviceCommonResponse {
    int32_t status;
    pb_callback_t reserved;
/* @@protoc_insertion_point(struct:DeviceCommonResponse) */
} DeviceCommonResponse;

typedef struct _DeviceOpenRequest {
    int32_t pwd;
    int32_t type;
    int64_t uid;
    int64_t timeStamp;
    pb_callback_t phoneNo;
/* @@protoc_insertion_point(struct:DeviceOpenRequest) */
} DeviceOpenRequest;

typedef struct _DeviceSetDeviceNameRequest {
    pb_callback_t name;
    pb_callback_t code;
    int32_t pairPWD;
    int32_t openPWD;
    int32_t openDelay;
    int32_t alarmDelay;
    int32_t installPurpose;
    pb_callback_t mqttServer;
    pb_callback_t ntpServer;
    int32_t isdhcp;
    pb_callback_t ip;
    pb_callback_t gateway;
    pb_callback_t mask;
    pb_callback_t dns;
    pb_callback_t groupId;
/* @@protoc_insertion_point(struct:DeviceSetDeviceNameRequest) */
} DeviceSetDeviceNameRequest;

/* Default values for struct fields */

/* Initializer values for message structs */
#define DeviceOpenRequest_init_default           {0, 0, 0, 0, {{NULL}, NULL}}
#define DeviceSetDeviceNameRequest_init_default  {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define DeviceSipInfoRequest_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define DeviceCommonResponse_init_default        {0, {{NULL}, NULL}}
#define DeviceOpenRequest_init_zero              {0, 0, 0, 0, {{NULL}, NULL}}
#define DeviceSetDeviceNameRequest_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define DeviceSipInfoRequest_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define DeviceCommonResponse_init_zero           {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceSipInfoRequest_centerSip_tag       1
#define DeviceSipInfoRequest_sipServer_tag       2
#define DeviceSipInfoRequest_sipAccount_tag      3
#define DeviceSipInfoRequest_sipPwd_tag          4
#define DeviceSipInfoRequest_sipServerSpare_tag  5
#define DeviceSipInfoRequest_sipAccountSpare_tag 6
#define DeviceSipInfoRequest_sipPwdSpare_tag     7
#define DeviceCommonResponse_status_tag          1
#define DeviceCommonResponse_reserved_tag        2
#define DeviceOpenRequest_pwd_tag                1
#define DeviceOpenRequest_type_tag               2
#define DeviceOpenRequest_uid_tag                3
#define DeviceOpenRequest_timeStamp_tag          4
#define DeviceOpenRequest_phoneNo_tag            5
#define DeviceSetDeviceNameRequest_name_tag      1
#define DeviceSetDeviceNameRequest_code_tag      2
#define DeviceSetDeviceNameRequest_pairPWD_tag   3
#define DeviceSetDeviceNameRequest_openPWD_tag   4
#define DeviceSetDeviceNameRequest_openDelay_tag 5
#define DeviceSetDeviceNameRequest_alarmDelay_tag 6
#define DeviceSetDeviceNameRequest_installPurpose_tag 7
#define DeviceSetDeviceNameRequest_mqttServer_tag 8
#define DeviceSetDeviceNameRequest_ntpServer_tag 9
#define DeviceSetDeviceNameRequest_isdhcp_tag    10
#define DeviceSetDeviceNameRequest_ip_tag        11
#define DeviceSetDeviceNameRequest_gateway_tag   12
#define DeviceSetDeviceNameRequest_mask_tag      13
#define DeviceSetDeviceNameRequest_dns_tag       14
#define DeviceSetDeviceNameRequest_groupId_tag   15

/* Struct field encoding specification for nanopb */
extern const pb_field_t DeviceOpenRequest_fields[6];
extern const pb_field_t DeviceSetDeviceNameRequest_fields[16];
extern const pb_field_t DeviceSipInfoRequest_fields[8];
extern const pb_field_t DeviceCommonResponse_fields[3];

/* Maximum encoded size of messages (where known) */
/* DeviceOpenRequest_size depends on runtime parameters */
/* DeviceSetDeviceNameRequest_size depends on runtime parameters */
/* DeviceSipInfoRequest_size depends on runtime parameters */
/* DeviceCommonResponse_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BLEPROTOCOL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
