/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Tue Sep 24 17:25:43 2019. */

#ifndef PB_TSLBLEPROTO_TSLBLECOMMON_PB_H_INCLUDED
#define PB_TSLBLEPROTO_TSLBLECOMMON_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TslBLEProto_TSLBLEDeviceInfoRequest {
    int32_t security;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceInfoRequest) */
} TslBLEProto_TSLBLEDeviceInfoRequest;

typedef struct _TslBLEProto_TSLBLEDeviceInfoResponse {
    int32_t security;
    pb_callback_t sn;
    int32_t dev_type;
    pb_callback_t manufacturers;
    pb_callback_t dev_name;
    pb_callback_t software_version;
    pb_callback_t hardware_version;
    pb_callback_t device_code;
    pb_callback_t location_code;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceInfoResponse) */
} TslBLEProto_TSLBLEDeviceInfoResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define TslBLEProto_TSLBLEDeviceInfoRequest_init_default {0}
#define TslBLEProto_TSLBLEDeviceInfoResponse_init_default {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceInfoRequest_init_zero {0}
#define TslBLEProto_TSLBLEDeviceInfoResponse_init_zero {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define TslBLEProto_TSLBLEDeviceInfoRequest_security_tag 1
#define TslBLEProto_TSLBLEDeviceInfoResponse_security_tag 1
#define TslBLEProto_TSLBLEDeviceInfoResponse_sn_tag 2
#define TslBLEProto_TSLBLEDeviceInfoResponse_dev_type_tag 3
#define TslBLEProto_TSLBLEDeviceInfoResponse_manufacturers_tag 4
#define TslBLEProto_TSLBLEDeviceInfoResponse_dev_name_tag 5
#define TslBLEProto_TSLBLEDeviceInfoResponse_software_version_tag 6
#define TslBLEProto_TSLBLEDeviceInfoResponse_hardware_version_tag 7
#define TslBLEProto_TSLBLEDeviceInfoResponse_device_code_tag 8
#define TslBLEProto_TSLBLEDeviceInfoResponse_location_code_tag 9

/* Struct field encoding specification for nanopb */
extern const pb_field_t TslBLEProto_TSLBLEDeviceInfoRequest_fields[2];
extern const pb_field_t TslBLEProto_TSLBLEDeviceInfoResponse_fields[10];

/* Maximum encoded size of messages (where known) */
#define TslBLEProto_TSLBLEDeviceInfoRequest_size 11
/* TslBLEProto_TSLBLEDeviceInfoResponse_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TSLBLECOMMON_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
