/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Fri Oct 18 15:50:12 2019. */

#ifndef PB_TSLBLEPROTO_TSLBLEUSER_PB_H_INCLUDED
#define PB_TSLBLEPROTO_TSLBLEUSER_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TslBLEProto_TSLBLEDeviceLOCKRequest {
    int32_t security;
    int32_t type;
    int64_t uid;
    int64_t timeStamp;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceLOCKRequest) */
} TslBLEProto_TSLBLEDeviceLOCKRequest;

/* Default values for struct fields */

/* Initializer values for message structs */
#define TslBLEProto_TSLBLEDeviceLOCKRequest_init_default {0, 0, 0, 0}
#define TslBLEProto_TSLBLEDeviceLOCKRequest_init_zero {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TslBLEProto_TSLBLEDeviceLOCKRequest_security_tag 1
#define TslBLEProto_TSLBLEDeviceLOCKRequest_type_tag 2
#define TslBLEProto_TSLBLEDeviceLOCKRequest_uid_tag 3
#define TslBLEProto_TSLBLEDeviceLOCKRequest_timeStamp_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t TslBLEProto_TSLBLEDeviceLOCKRequest_fields[5];

/* Maximum encoded size of messages (where known) */
#define TslBLEProto_TSLBLEDeviceLOCKRequest_size 44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TSLBLEUSER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
