/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Fri Oct 18 15:50:12 2019. */

#include "TSLBleUser.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TslBLEProto_TSLBLEDeviceLOCKRequest_fields[5] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TslBLEProto_TSLBLEDeviceLOCKRequest, security, security, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, TslBLEProto_TSLBLEDeviceLOCKRequest, type, security, 0),
    PB_FIELD(  3, INT64   , SINGULAR, STATIC  , OTHER, TslBLEProto_TSLBLEDeviceLOCKRequest, uid, type, 0),
    PB_FIELD(  4, INT64   , SINGULAR, STATIC  , OTHER, TslBLEProto_TSLBLEDeviceLOCKRequest, timeStamp, uid, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
