/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Sep 25 14:34:26 2019. */

#include "TSLBleWizard.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TslBLEProto_TSLBLEDeviceSetPWDRequest_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TslBLEProto_TSLBLEDeviceSetPWDRequest, security, security, 0),
    PB_LAST_FIELD
};

const pb_field_t TslBLEProto_TSLBLEDeviceSetGUPRequest_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, TslBLEProto_TSLBLEDeviceSetGUPRequest, groupid, groupid, 0),
    PB_LAST_FIELD
};

const pb_field_t TslBLEProto_TSLBLEDeviceSetMQTTNETRequest_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, TslBLEProto_TSLBLEDeviceSetMQTTNETRequest, ipport, ipport, 0),
    PB_LAST_FIELD
};

const pb_field_t TslBLEProto_TSLBLEDeviceSetDEVNETRequest_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TslBLEProto_TSLBLEDeviceSetDEVNETRequest, isdhcp, isdhcp, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceSetDEVNETRequest, ip, isdhcp, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceSetDEVNETRequest, msk, ip, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceSetDEVNETRequest, gw, msk, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceSetDEVNETRequest, dns, gw, 0),
    PB_LAST_FIELD
};

const pb_field_t TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest, code, code, 0),
    PB_LAST_FIELD
};

const pb_field_t TslBLEProto_TSLBLEDeviceSetDEVICECODERequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, TslBLEProto_TSLBLEDeviceSetDEVICECODERequest, code, code, 0),
    PB_LAST_FIELD
};

const pb_field_t TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest, pwd, pwd, 0),
    PB_LAST_FIELD
};

const pb_field_t TslBLEProto_TSLBLEDeviceCommonResponse_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TslBLEProto_TSLBLEDeviceCommonResponse, status, status, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceCommonResponse, reserved, status, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
