/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Sep 24 17:25:43 2019. */

#include "TSLBleCommon.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TslBLEProto_TSLBLEDeviceInfoRequest_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TslBLEProto_TSLBLEDeviceInfoRequest, security, security, 0),
    PB_LAST_FIELD
};

const pb_field_t TslBLEProto_TSLBLEDeviceInfoResponse_fields[10] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TslBLEProto_TSLBLEDeviceInfoResponse, security, security, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceInfoResponse, sn, security, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, TslBLEProto_TSLBLEDeviceInfoResponse, dev_type, sn, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceInfoResponse, manufacturers, dev_type, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceInfoResponse, dev_name, manufacturers, 0),
    PB_FIELD(  6, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceInfoResponse, software_version, dev_name, 0),
    PB_FIELD(  7, STRING  , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceInfoResponse, hardware_version, software_version, 0),
    PB_FIELD(  8, BYTES   , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceInfoResponse, device_code, hardware_version, 0),
    PB_FIELD(  9, BYTES   , SINGULAR, CALLBACK, OTHER, TslBLEProto_TSLBLEDeviceInfoResponse, location_code, device_code, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
