/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Wed Sep 25 14:34:26 2019. */

#ifndef PB_TSLBLEPROTO_TSLBLEWIZARD_PB_H_INCLUDED
#define PB_TSLBLEPROTO_TSLBLEWIZARD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _TslBLEProto_TSLBLEDeviceSetDEVICECODERequest {
    pb_callback_t code;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceSetDEVICECODERequest) */
} TslBLEProto_TSLBLEDeviceSetDEVICECODERequest;

typedef struct _TslBLEProto_TSLBLEDeviceSetGUPRequest {
    pb_callback_t groupid;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceSetGUPRequest) */
} TslBLEProto_TSLBLEDeviceSetGUPRequest;

typedef struct _TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest {
    pb_callback_t code;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest) */
} TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest;

typedef struct _TslBLEProto_TSLBLEDeviceSetMQTTNETRequest {
    pb_callback_t ipport;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceSetMQTTNETRequest) */
} TslBLEProto_TSLBLEDeviceSetMQTTNETRequest;

typedef struct _TslBLEProto_TSLBLEDeviceCommonResponse {
    int32_t status;
    pb_callback_t reserved;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceCommonResponse) */
} TslBLEProto_TSLBLEDeviceCommonResponse;

typedef struct _TslBLEProto_TSLBLEDeviceSetDEVNETRequest {
    int32_t isdhcp;
    pb_callback_t ip;
    pb_callback_t msk;
    pb_callback_t gw;
    pb_callback_t dns;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceSetDEVNETRequest) */
} TslBLEProto_TSLBLEDeviceSetDEVNETRequest;

typedef struct _TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest {
    int32_t pwd;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest) */
} TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest;

typedef struct _TslBLEProto_TSLBLEDeviceSetPWDRequest {
    int32_t security;
/* @@protoc_insertion_point(struct:TslBLEProto_TSLBLEDeviceSetPWDRequest) */
} TslBLEProto_TSLBLEDeviceSetPWDRequest;

/* Default values for struct fields */

/* Initializer values for message structs */
#define TslBLEProto_TSLBLEDeviceSetPWDRequest_init_default {0}
#define TslBLEProto_TSLBLEDeviceSetGUPRequest_init_default {{{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetMQTTNETRequest_init_default {{{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetDEVNETRequest_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest_init_default {{{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetDEVICECODERequest_init_default {{{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest_init_default {0}
#define TslBLEProto_TSLBLEDeviceCommonResponse_init_default {0, {{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetPWDRequest_init_zero {0}
#define TslBLEProto_TSLBLEDeviceSetGUPRequest_init_zero {{{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetMQTTNETRequest_init_zero {{{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetDEVNETRequest_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest_init_zero {{{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetDEVICECODERequest_init_zero {{{NULL}, NULL}}
#define TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest_init_zero {0}
#define TslBLEProto_TSLBLEDeviceCommonResponse_init_zero {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define TslBLEProto_TSLBLEDeviceSetDEVICECODERequest_code_tag 1
#define TslBLEProto_TSLBLEDeviceSetGUPRequest_groupid_tag 1
#define TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest_code_tag 1
#define TslBLEProto_TSLBLEDeviceSetMQTTNETRequest_ipport_tag 1
#define TslBLEProto_TSLBLEDeviceCommonResponse_status_tag 1
#define TslBLEProto_TSLBLEDeviceCommonResponse_reserved_tag 2
#define TslBLEProto_TSLBLEDeviceSetDEVNETRequest_isdhcp_tag 1
#define TslBLEProto_TSLBLEDeviceSetDEVNETRequest_ip_tag 2
#define TslBLEProto_TSLBLEDeviceSetDEVNETRequest_msk_tag 3
#define TslBLEProto_TSLBLEDeviceSetDEVNETRequest_gw_tag 4
#define TslBLEProto_TSLBLEDeviceSetDEVNETRequest_dns_tag 5
#define TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest_pwd_tag 1
#define TslBLEProto_TSLBLEDeviceSetPWDRequest_security_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t TslBLEProto_TSLBLEDeviceSetPWDRequest_fields[2];
extern const pb_field_t TslBLEProto_TSLBLEDeviceSetGUPRequest_fields[2];
extern const pb_field_t TslBLEProto_TSLBLEDeviceSetMQTTNETRequest_fields[2];
extern const pb_field_t TslBLEProto_TSLBLEDeviceSetDEVNETRequest_fields[6];
extern const pb_field_t TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest_fields[2];
extern const pb_field_t TslBLEProto_TSLBLEDeviceSetDEVICECODERequest_fields[2];
extern const pb_field_t TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest_fields[2];
extern const pb_field_t TslBLEProto_TSLBLEDeviceCommonResponse_fields[3];

/* Maximum encoded size of messages (where known) */
#define TslBLEProto_TSLBLEDeviceSetPWDRequest_size 11
/* TslBLEProto_TSLBLEDeviceSetGUPRequest_size depends on runtime parameters */
/* TslBLEProto_TSLBLEDeviceSetMQTTNETRequest_size depends on runtime parameters */
/* TslBLEProto_TSLBLEDeviceSetDEVNETRequest_size depends on runtime parameters */
/* TslBLEProto_TSLBLEDeviceSetLOCATIONCODERequest_size depends on runtime parameters */
/* TslBLEProto_TSLBLEDeviceSetDEVICECODERequest_size depends on runtime parameters */
#define TslBLEProto_TSLBLEDeviceSetLOCKPWDRequest_size 11
/* TslBLEProto_TSLBLEDeviceCommonResponse_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TSLBLEWIZARD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
